// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on BUC

package item

import (
	"fmt"
)

const _BUC_name = "BUCUnknownNoncursedUncursedBlessedCursed"

var _BUC_index = [...]uint8{0, 10, 19, 27, 34, 40}

func (i BUC) String() string {
	if i < 0 || i+1 >= BUC(len(_BUC_index)) {
		return fmt.Sprintf("BUC(%d)", i)
	}
	return _BUC_name[_BUC_index[i]:_BUC_index[i+1]]
}
