// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on Terrain

package square

import (
	"fmt"
)

const _Terrain_name = "UnexploredStaircaseUpStaircaseDownLadderUpLadderDownAltarSinkFountainTreeTrapDoorClosedDoorOpenHorizDoorOpenVertDoorOpenDestroyedWallDrawbridgeIronBarsFloorCorridorThroneGraveWaterIceLavaCloudAirSolidRock"

var _Terrain_index = [...]uint8{0, 10, 21, 34, 42, 52, 57, 61, 69, 73, 77, 87, 100, 112, 129, 133, 143, 151, 156, 164, 170, 175, 180, 183, 187, 192, 195, 204}

func (i Terrain) String() string {
	if i < 0 || i+1 >= Terrain(len(_Terrain_index)) {
		return fmt.Sprintf("Terrain(%d)", i)
	}
	return _Terrain_name[_Terrain_index[i]:_Terrain_index[i+1]]
}
